
version: '3.4'
services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi

    
    build:
      context: .
      dockerfile: ./Dockerfile

   
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Conectionstring=Server=db;Database=Flowers_store

    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    container_name: mssql